# Generated by Django 5.0.3 on 2024-04-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResultt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='Unknown', max_length=255)),
                ('javadoc_comment_count', models.IntegerField()),
                ('other_comment_count', models.IntegerField()),
                ('code_line_count', models.IntegerField()),
                ('loc_count', models.IntegerField()),
                ('function_count', models.IntegerField()),
                ('comment_deviation_percentage', models.FloatField()),
            ],
        ),
    ]
